### ISSUE TITLE
I hope weron can support network tunnels over WebRTC

### ISSUE THREAD

**Issue by vip123456789** [pojntfx/weron#11]
I hope weron can support network tunnels over WebRTC, like this: https://github.com/rtctunnel/rtctunnel

Thanks!

**Comment by pojntfx** [comment]
You can already do that with the included library! See https://github.com/pojntfx/weron#8-write-your-own-protocol-with-wrtcconn, all you need to do is to implement the `listen`/`dial` handlers and then `io.Copy` between them and the weron connections.
