### ISSUE TITLE
Can you give an example of communication between the two parties based on the negotiated token?

### ISSUE THREAD

**Issue by hktalent** [pojntfx/weron#13]
$ uuidgen
95318F39-C615-4485-A37A-1DFDBF0C4C7A

Can you give an example of communication between the two parties based on the negotiated token?

A and B use 95318F39-C615-4485-A37A-1DFDBF0C4C7A to establish an example of p2p communication

**Comment by pojntfx** [comment]
Take a look a https://github.com/pojntfx/weron/blob/main/examples/weron-echo/main.go for a simple usage example.
