### ISSUE TITLE
How would I go about to implement this in my own programs? 

### ISSUE THREAD

**Issue by nilsdev** [pojntfx/weron#4]
I'm sorry to spam your issues feed with this, but I'm new to Golang and do not quite get how i can use your great software in my own projects.

My goal would be a simple binary I could send friends, so they can access my homelabs sites. Some of them might not be able / willing to run the commands (no offense to them). I would love to just send them a simple GUI with a couple of buttons (I've done this before, and it worked perfectly with go). 

I'm obviously not asking for the entire program, just a simple hello world on how to use the api's :) 

Again, sorry for posting this here, but I think it could help a lot of people to start implementing your vpn solution.

**Comment by matti** [comment]
it is a valid question - I would suggest you to just distribute the weron binary to them with similar args as in the README

**Comment by pojntfx** [comment]
@nilsdev I've added a simple example here: https://github.com/pojntfx/weron/blob/main/examples/weron-echo/main.go feel free to reopen or ask on Matrix (https://matrix.to/#/#weron:matrix.org?via=matrix.org) it you need more help ^^

**Comment by nilsdev** [comment]
@pojntfx thanks a lot!
@matti this way my solution until now, but I love to hack my "own" stuff together. I'm not protecting / sharing anything too important with this. Shouldn't  be a big problem if I fuck something up :)
