### ISSUE TITLE
Potential issues in Russia

### ISSUE THREAD

**Issue by ValdikSS** [pojntfx/weron#5]
Hi there,
this project uses pion WebRTC library, the DTLS ClientHello fingerprint of which is blocked in Russia on government Deep Packet Inspection hardware, as Tor Project's Snowflake censorship circumvention method also uses pion.
Tor changed the fingerprint since the beginning of the censorship, however the original pion is still getting filtered.

https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/issues/40014#note_2764715

**Comment by pojntfx** [comment]
Thanks a lot for bringing this up! Looking into how to circumvent it now.

**Comment by pojntfx** [comment]
@ValdikSS From my understanding of https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/merge_requests/66/diffs#c47645c391ad0571c40779079363c9d48412e18b, fixing this should mean updating the Pion `dtls` library to `>= v2.0.12`, right? If I interpret https://github.com/pojntfx/weron/blob/main/go.sum#L351-L352 correctly, this should already be the case, could you confirm (I'm based in the EU so I can't really test it with anything other than a VPN to Russia, which doesn't seem to be an issue)?

**Comment by pojntfx** [comment]
Closing this due to lack of feedback; if the problem persists, feel free to reopen.
