### ISSUE TITLE
Android / iOS mobile clients

### ISSUE THREAD

**Issue by mrbluecoat** [pojntfx/weron#8]
Any plans to support Android / iOS?

**Comment by pojntfx** [comment]
Its definitely possible! I mentioned it before on Matrix - one would have to build a library that interacts with the Android VpnService (https://developer.android.com/reference/android/net/VpnService)  for this to be possible, but I do not have the ressources to work on that for the time being.

**Comment by afgarcia86** [comment]
@mrbluecoat did you happen to find a solution?

**Comment by ignoramous** [comment]
> one would have to build a library that interacts with the [Android VpnService](https://developer.android.com/reference/android/net/VpnService) for this to be possible, but I do not have the resources

An Android-only anti-censorship FOSS app (licensed under Apache v2) I co-develop was looking to add weron but the AGPL license is incompatible with Apache :(
